#!/usr/bin/env python3
"""Live diagnostic for the Telegram feed.

Connects to Telegram, fetches the last N messages from po_broker_bot,
runs each through parse_signal, then stays listening for new ones.

Usage (from repo root):
    python3 tools/test_telegram_feed.py [--history N]

Requires .env with:
    TELEGRAM_API_ID
    TELEGRAM_API_HASH
    TELEGRAM_SESSION_STRING   (preferred — generated by tools/gen_telegram_session.py)
    OR TELEGRAM_PHONE         (for file-based session on first run)
"""

import argparse
import asyncio
import sys
from datetime import timezone
from pathlib import Path

# Ensure repo root is on sys.path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config.settings import settings
from telegram_feed.parser import parse_signal
from utils.logger import setup_logger, log

PROJECT_ROOT = Path(__file__).parent.parent

DIVIDER = "─" * 60


def _print_parsed(raw: str, idx: int | None = None) -> None:
    prefix = f"[{idx}] " if idx is not None else "[new] "
    log.info(DIVIDER)
    log.info("%sRAW: %s", prefix, raw.strip()[:200])
    signal = parse_signal(raw)
    if signal is None:
        log.warning("%sPARSED: ✗  (unparseable — message format not recognised)", prefix)
    else:
        log.info(
            "%sPARSED: ✓  pair=%-16s dir=%-4s expiry=%3ds  wr=%s",
            prefix,
            signal.pair,
            signal.direction,
            signal.expiry_seconds,
            f"{signal.stated_win_rate:.0%}" if signal.stated_win_rate is not None else "N/A",
        )


async def main(history_count: int) -> None:
    setup_logger(PROJECT_ROOT, level="DEBUG")

    try:
        from telethon import TelegramClient, events as tg_events
        from telethon.sessions import StringSession
    except ImportError:
        log.error("Telethon not installed. Run: pip install telethon")
        sys.exit(1)

    if not settings.telegram_api_id or not settings.telegram_api_hash:
        log.error(
            "TELEGRAM_API_ID and TELEGRAM_API_HASH must be set in .env\n"
            "  Get them from https://my.telegram.org"
        )
        sys.exit(1)

    session_string = settings.telegram_session_string
    if session_string:
        session = StringSession(session_string)
        log.info("Using StringSession (cloud/headless mode)")
    elif settings.telegram_phone:
        session = settings.telegram_session
        log.info("Using file session '%s.session' (local mode)", settings.telegram_session)
    else:
        log.error(
            "No session configured. Either:\n"
            "  1. Run tools/gen_telegram_session.py locally and set TELEGRAM_SESSION_STRING, or\n"
            "  2. Set TELEGRAM_PHONE for a file-based local session."
        )
        sys.exit(1)

    client = TelegramClient(session, settings.telegram_api_id, settings.telegram_api_hash)

    await client.start(phone=settings.telegram_phone if not session_string else None)
    log.info("Connected to Telegram ✓")

    bot_username = settings.signal_bot_username
    log.info("Signal bot: @%s", bot_username)
    log.info(DIVIDER)

    # ── Fetch message history ────────────────────────────────────────────────
    if history_count > 0:
        log.info("Fetching last %d messages from @%s ...", history_count, bot_username)
        try:
            messages = await client.get_messages(bot_username, limit=history_count)
            if not messages:
                log.warning("No message history found. Have you started the bot? Send /start to @%s first.", bot_username)
            else:
                log.info("Got %d messages:", len(messages))
                for i, msg in enumerate(reversed(messages), 1):
                    text = msg.raw_text or ""
                    if text.strip():
                        _print_parsed(text, idx=i)
                    else:
                        log.debug("[%d] (non-text message, skipping)", i)
        except Exception as e:
            log.error("Could not fetch history: %s", e)

    # ── Live listener ─────────────────────────────────────────────────────────
    log.info(DIVIDER)
    log.info("Listening for NEW messages from @%s (Ctrl+C to stop) ...", bot_username)

    @client.on(tg_events.NewMessage(from_users=bot_username))
    async def _on_message(event):
        text = event.raw_text or ""
        if text.strip():
            _print_parsed(text)
        else:
            log.debug("[new] (non-text message, skipping)")

    try:
        await client.run_until_disconnected()
    except (KeyboardInterrupt, asyncio.CancelledError):
        log.info("Stopped.")
    finally:
        await client.disconnect()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Live Telegram feed diagnostic")
    parser.add_argument(
        "--history", type=int, default=20, metavar="N",
        help="Number of past messages to fetch and parse (default: 20, 0 = skip)",
    )
    args = parser.parse_args()
    asyncio.run(main(history_count=args.history))
